// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// minimax_r
List minimax_r(IntegerMatrix tablero, int profundidad, bool maximizandoIA);
RcppExport SEXP _conn4R_minimax_r(SEXP tableroSEXP, SEXP profundidadSEXP, SEXP maximizandoIASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type tablero(tableroSEXP);
    Rcpp::traits::input_parameter< int >::type profundidad(profundidadSEXP);
    Rcpp::traits::input_parameter< bool >::type maximizandoIA(maximizandoIASEXP);
    rcpp_result_gen = Rcpp::wrap(minimax_r(tablero, profundidad, maximizandoIA));
    return rcpp_result_gen;
END_RCPP
}
// evaluar_posicion_cpp
int evaluar_posicion_cpp(IntegerMatrix tablero);
RcppExport SEXP _conn4R_evaluar_posicion_cpp(SEXP tableroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type tablero(tableroSEXP);
    rcpp_result_gen = Rcpp::wrap(evaluar_posicion_cpp(tablero));
    return rcpp_result_gen;
END_RCPP
}
// juego_terminado_cpp
List juego_terminado_cpp(IntegerMatrix tablero);
RcppExport SEXP _conn4R_juego_terminado_cpp(SEXP tableroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type tablero(tableroSEXP);
    rcpp_result_gen = Rcpp::wrap(juego_terminado_cpp(tablero));
    return rcpp_result_gen;
END_RCPP
}
// realizar_jugada_r
IntegerMatrix realizar_jugada_r(IntegerMatrix tablero, int columna, int jugador);
RcppExport SEXP _conn4R_realizar_jugada_r(SEXP tableroSEXP, SEXP columnaSEXP, SEXP jugadorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type tablero(tableroSEXP);
    Rcpp::traits::input_parameter< int >::type columna(columnaSEXP);
    Rcpp::traits::input_parameter< int >::type jugador(jugadorSEXP);
    rcpp_result_gen = Rcpp::wrap(realizar_jugada_r(tablero, columna, jugador));
    return rcpp_result_gen;
END_RCPP
}
// jugadas_disponibles_r
IntegerVector jugadas_disponibles_r(IntegerMatrix tablero);
RcppExport SEXP _conn4R_jugadas_disponibles_r(SEXP tableroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type tablero(tableroSEXP);
    rcpp_result_gen = Rcpp::wrap(jugadas_disponibles_r(tablero));
    return rcpp_result_gen;
END_RCPP
}
// ordenar_jugadas_r
DataFrame ordenar_jugadas_r(IntegerMatrix tablero, int turno);
RcppExport SEXP _conn4R_ordenar_jugadas_r(SEXP tableroSEXP, SEXP turnoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type tablero(tableroSEXP);
    Rcpp::traits::input_parameter< int >::type turno(turnoSEXP);
    rcpp_result_gen = Rcpp::wrap(ordenar_jugadas_r(tablero, turno));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_conn4R_minimax_r", (DL_FUNC) &_conn4R_minimax_r, 3},
    {"_conn4R_evaluar_posicion_cpp", (DL_FUNC) &_conn4R_evaluar_posicion_cpp, 1},
    {"_conn4R_juego_terminado_cpp", (DL_FUNC) &_conn4R_juego_terminado_cpp, 1},
    {"_conn4R_realizar_jugada_r", (DL_FUNC) &_conn4R_realizar_jugada_r, 3},
    {"_conn4R_jugadas_disponibles_r", (DL_FUNC) &_conn4R_jugadas_disponibles_r, 1},
    {"_conn4R_ordenar_jugadas_r", (DL_FUNC) &_conn4R_ordenar_jugadas_r, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_conn4R(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
