// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// minimax
List minimax(IntegerMatrix tablero, int profundidad, bool maximizandoIA);
RcppExport SEXP _conn4R_minimax(SEXP tableroSEXP, SEXP profundidadSEXP, SEXP maximizandoIASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type tablero(tableroSEXP);
    Rcpp::traits::input_parameter< int >::type profundidad(profundidadSEXP);
    Rcpp::traits::input_parameter< bool >::type maximizandoIA(maximizandoIASEXP);
    rcpp_result_gen = Rcpp::wrap(minimax(tablero, profundidad, maximizandoIA));
    return rcpp_result_gen;
END_RCPP
}
// evaluar_posicion
int evaluar_posicion(IntegerMatrix tablero);
RcppExport SEXP _conn4R_evaluar_posicion(SEXP tableroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type tablero(tableroSEXP);
    rcpp_result_gen = Rcpp::wrap(evaluar_posicion(tablero));
    return rcpp_result_gen;
END_RCPP
}
// juego_terminado
List juego_terminado(IntegerMatrix tablero);
RcppExport SEXP _conn4R_juego_terminado(SEXP tableroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type tablero(tableroSEXP);
    rcpp_result_gen = Rcpp::wrap(juego_terminado(tablero));
    return rcpp_result_gen;
END_RCPP
}
// realizar_jugada
IntegerMatrix realizar_jugada(IntegerMatrix tablero, int columna, int jugador);
RcppExport SEXP _conn4R_realizar_jugada(SEXP tableroSEXP, SEXP columnaSEXP, SEXP jugadorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type tablero(tableroSEXP);
    Rcpp::traits::input_parameter< int >::type columna(columnaSEXP);
    Rcpp::traits::input_parameter< int >::type jugador(jugadorSEXP);
    rcpp_result_gen = Rcpp::wrap(realizar_jugada(tablero, columna, jugador));
    return rcpp_result_gen;
END_RCPP
}
// jugadas_disponibles
IntegerVector jugadas_disponibles(IntegerMatrix tablero);
RcppExport SEXP _conn4R_jugadas_disponibles(SEXP tableroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type tablero(tableroSEXP);
    rcpp_result_gen = Rcpp::wrap(jugadas_disponibles(tablero));
    return rcpp_result_gen;
END_RCPP
}
// ordenar_jugadas
DataFrame ordenar_jugadas(IntegerMatrix tablero, int turno);
RcppExport SEXP _conn4R_ordenar_jugadas(SEXP tableroSEXP, SEXP turnoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type tablero(tableroSEXP);
    Rcpp::traits::input_parameter< int >::type turno(turnoSEXP);
    rcpp_result_gen = Rcpp::wrap(ordenar_jugadas(tablero, turno));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_conn4R_minimax", (DL_FUNC) &_conn4R_minimax, 3},
    {"_conn4R_evaluar_posicion", (DL_FUNC) &_conn4R_evaluar_posicion, 1},
    {"_conn4R_juego_terminado", (DL_FUNC) &_conn4R_juego_terminado, 1},
    {"_conn4R_realizar_jugada", (DL_FUNC) &_conn4R_realizar_jugada, 3},
    {"_conn4R_jugadas_disponibles", (DL_FUNC) &_conn4R_jugadas_disponibles, 1},
    {"_conn4R_ordenar_jugadas", (DL_FUNC) &_conn4R_ordenar_jugadas, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_conn4R(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
