# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jugadas_disponibles_cpp <- function(tablero) {
    .Call(`_conn4R_jugadas_disponibles_cpp`, tablero)
}

realizar_jugada_cpp <- function(tablero, columna, jugador) {
    .Call(`_conn4R_realizar_jugada_cpp`, tablero, columna, jugador)
}

suma <- function(x, y) {
    .Call(`_conn4R_suma`, x, y)
}

ordenar_jugadas_cpp <- function(tablero, turno) {
    .Call(`_conn4R_ordenar_jugadas_cpp`, tablero, turno)
}

