# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

minimax_r <- function(tablero, profundidad, maximizandoIA) {
    .Call(`_conn4R_minimax_r`, tablero, profundidad, maximizandoIA)
}

evaluar_posicion_cpp <- function(tablero) {
    .Call(`_conn4R_evaluar_posicion_cpp`, tablero)
}

juego_terminado_cpp <- function(tablero) {
    .Call(`_conn4R_juego_terminado_cpp`, tablero)
}
